#!/bin/bash
# Generate version changelog
# Usage: ./generate_changelog.sh <version> <prev_version> <output_file>

VERSION="$1"
PREV_VERSION="$2"
OUTPUT_FILE="$3"

if [ -z "$VERSION" ] || [ -z "$OUTPUT_FILE" ]; then
    echo "Error: Version and output file required"
    exit 1
fi

DATE=$(date +"%Y-%m-%d")

# Get changes
if [ -z "$PREV_VERSION" ]; then
    CHANGES=$(git log --oneline -20)
    DIFF_STATS=$(git diff --stat HEAD)
else
    CHANGES=$(git log "$PREV_VERSION"..HEAD --oneline)
    DIFF_STATS=$(git diff --stat "$PREV_VERSION" HEAD)
fi

# Categorize changes (simple heuristic)
FEATURES=$(echo "$CHANGES" | grep -iE "feat|feature|新增|功能" | head -10)
FIXES=$(echo "$CHANGES" | grep -iE "fix|bug|修复|修正" | head -10)
IMPROVEMENTS=$(echo "$CHANGES" | grep -iE "improve|refactor|perf|优化|改进" | head -10)

cat > "$OUTPUT_FILE" <<EOF
# Version $VERSION

**Release Date**: $DATE  
**Status**: ✅ Tested  
**Previous Version**: ${PREV_VERSION:-N/A}

## Overview

This release includes updates since the previous version.

## What's New (Features)

$(echo "$FEATURES" | sed 's/^/- /' || echo "- No new features")

## Bug Fixes

$(echo "$FIXES" | sed 's/^/- /' || echo "- No bug fixes")

## Improvements

$(echo "$IMPROVEMENTS" | sed 's/^/- /' || echo "- No improvements")

## Changed Files

\`\`\`
$DIFF_STATS
\`\`\`

## Recent Commits

\`\`\`
$CHANGES
\`\`\`

## Rollback Commands

\`\`\`bash
# To rollback to previous version:
git checkout v$PREV_VERSION
git reset --hard v$PREV_VERSION

# To delete this tag:
git tag -d v$VERSION
\`\`\`

---

*Generated by project-versioning skill*
EOF

echo "Created changelog: $OUTPUT_FILE"
